version: '2'
services:
#    angular:
#        image: alexsuch/angular-cli
#        restart: always
#        ports:
#            - "4200:4200"
#        links:
#            - api
#        volumes:
#            - ./backend:/backend
#        container_name: bcs_ng
#        hostname: bcs-ng
#        command: /bin/sh

#    serve:
#        build: ./backend
#        command: ng serve --host 0.0.0.0
#        environment:
#            NODE_ENV: development
#        volumes:
#            - .:/backend
#            - /backend/node_modules
#        ports:
#            - "4200:4200"

    api:
        image: shincoder/homestead:php7.0
        restart: always
        ports:
            - "80:80" # web
        links:
            - mariadb
        container_name: bcs_web
        volumes:
            - ./:/bcs
        env_file: ./.env
        hostname: bcs-web
#        command: bash -c "/serve.sh bms.dev /bms/public"

    mariadb:
        image: tutum/mariadb
        restart: always
        ports:
            - "33060:3306"
#        environment:
#            MARIADB_USER: root # cannot be changed ( for info. only )
#            MARIADB_PASS: secret
        container_name: bcs_db
        hostname: bcs-db
